
version: "3"

services:
  db:
    image: postgres:10-alpine
    environment: 
      - POSTGRES_DB=bookings
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=supersecretpassword
      - POSTGRES_HOST_AUTH_METHOD=trust
    ports:
      - "127.0.0.1:5432:5432"